### ISSUE TITLE
Create new set of pages for tracking hosts

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#159]
- [x] Create Host namespace
- [x] Create Form:Host
- [x] Create Template:Host
- [x] Modify Template:Whois to set property as page with namespace
- [x] Change Property:Has netblock organization to a page
- [x] Set property to automatically create pages with form

**Comment by jthingelstad** [comment]
Namespace created and [Host:Hosts](https://wikiapiary.com/wiki/Host:Hosts) stubbed out.

**Comment by plexish** [comment]
Made a basic Template:Host.

**Comment by plexish** [comment]
Do we want to go with Host:Main_Page or Host:Hosts? The former is used by all the others, so if we're going with the latter we should move the others for consistency imo.

Also, made basic [Main_Page](https://wikiapiary.com/wiki/Host:Main_Page), feel free to merge if you'd prefer Host:Hosts.

**Comment by jthingelstad** [comment]
Thank you @etesp! I think it’s a good enough start. I just modified the property to start creating all the host pages.

And I do think #153 is a good idea so left it Host:Hosts with a redirect on Host:Main_Page.
